DZ_TUBE = 101;         
DZ_POMMEL_THREAD = 10;
DZ_PADDING = 1.0;     

DZ_CHASSIS = DZ_TUBE - DZ_POMMEL_THREAD - DZ_PADDING;
DZ_PCB = 27;
DZ_HOLDER = DZ_CHASSIS - DZ_PCB; 

H_BUTTRESS			= 4;
D_AFT				= 32.0;
R_AFT 				= D_AFT / 2;
D_FORWARD			= 25.4;
R_FORWARD           = D_FORWARD / 2;
