M_LED_HOLDER_FRONT	= 45;
M_LED_HOLDER_BACK	= 38;
M_SWITCH_CENTER		= 30;	// FIXME
M_TRANSITION		= 10;
M_0					= 0;
M_WAY_BACK			= -20;

H_FAR				= 200;

MM_TO_INCHES = 1 / 25.4;
INCHES_TO_MM = 25.4;

D_FORWARD			= 1.00 * INCHES_TO_MM;
R_FORWARD 			= D_FORWARD / 2;
D_AFT				= 31.4;
R_AFT 				= D_AFT / 2;

Y_SWITCH			= 9.6;
D_SWITCH			= 12.5;

D_SABER_OUTER		= 37.5;

D_PORT_SCREW		= 0.5 * INCHES_TO_MM;
R_PORT_SCREW 		= D_PORT_SCREW / 2;
