#ifndef OPEN_SABER_AUDIO_PINS_INCLUDED
#define OPEN_SABER_AUDIO_PINS_INCLUDED

#define PIN_SDCARD_CS    10
#define PIN_SDCARD_MOSI  11
#define PIN_SDCARD_SCK   13
#define PIN_AMP_EN		 14

#define SABER_SOUND_ON SABER_SOUND_SD

#endif // OPEN_SABER_AUDIO_PINS_INCLUDED
