MM_TO_INCHES = 1 / 25.4;
INCHES_TO_MM = 25.4;

D_FORWARD			= 1.00 * INCHES_TO_MM;
D_AFT				= 31.4;
R_FORWARD 			= D_FORWARD / 2;
R_AFT 				= D_AFT / 2;
D_SABER_OUTER		= 37.5;

D_PORT_SCREW		= 0.5 * INCHES_TO_MM;
R_PORT_SCREW 		= D_PORT_SCREW / 2;

FACES 				= 90;
GAP					= 0.200;
