MM_TO_INCHES = 1 / 25.4;
INCHES_TO_MM = 25.4;

D_FORWARD			= 1.00 * INCHES_TO_MM;
D_AFT				= 1.25 * INCHES_TO_MM;	// FIXME
R_FORWARD 			= D_FORWARD / 2;
R_AFT 				= D_AFT / 2;

D_PORT_SCREW		= 0.5 * INCHES_TO_MM;	// FIXME
R_PORT_SCREW 		= D_PORT_SCREW / 2;
PORT_SCREW_PAD		= 5;
PORT_LEN			= D_PORT_SCREW + PORT_SCREW_PAD * 2;

H_PORT				= 8;	// FIXME

FACES 				= 90;
